### ISSUE TITLE
[DOC]: Code blocks in libcu++ docs are hard to read

### ISSUE THREAD

**Issue by Nyrio** [NVIDIA/cccl#1481]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

Currently, code blocks have a background color for the block but also one for the text. I find that this makes them hard to read.

My suggestion is to remove the text background color and make the block background color darker.

Before:

![css_before](https://github.com/NVIDIA/cccl/assets/17441062/8125e106-652f-4cac-baf4-1e193c82bc33)

After:

![css_after_2](https://github.com/NVIDIA/cccl/assets/17441062/bc935382-c1cc-4ece-944e-00e9dd6e3f56)

In the CSS, one could remove:

```css
div.highlighter-rouge, pre.highlight code {
  background-color: #111 !important;
}
```

And update:

```css
.highlighter-rouge div.highlight
{ background: #1a1a1a; }

.highlighter-rouge div.highlight pre
{ background: #1a1a1a; }
```

_edit: the rule needs to be more specific than defaults to override them_

Example: https://nvidia.github.io/cccl/libcudacxx/ptx.html#stasync
