### ISSUE TITLE
[BUG]: thrust::universal_vector tests fail (C++14 on CTK 11.1 & gcc 6)

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#227]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

Thrust

### Describe the bug

The following test fails for C++14 on CTK 11.1 & gcc 6
```
thrust.cpp.cuda.cpp14.test.cuda.device_side_universal_vector.cdp_0
```

### How to Reproduce

```
cd ~/cccl
  time ././ci/test_thrust.sh "g++" "14" "70"
  shell: su coder {0}
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    SCCACHE_BUCKET: rapids-sccache-devs
    SCCACHE_REGION: us-east-2
    SCCACHE_IDLE_TIMEOUT: [3](https://github.com/NVIDIA/cccl/actions/runs/5469818591/jobs/9959247698?pr=167#step:8:3)27[6](https://github.com/NVIDIA/cccl/actions/runs/5469818591/jobs/9959247698?pr=167#step:8:6)[8](https://github.com/NVIDIA/cccl/actions/runs/5469818591/jobs/9959247698?pr=167#step:8:8)
    SCCACHE_S3_USE_SSL: true
    SCCACHE_S3_NO_CREDENTIALS: false
```

### Expected behavior

Test doesn't fail

### Reproduction link

https://github.com/NVIDIA/cccl/actions/runs/5469818591/jobs/9959247698?pr=167
